# Setup
title:              My 30 Days of Hacking Challenge
title_separator:    "-"
name:               &name "Gyan Ranjan" # &name is a YAML anchor which can be *referenced later
email:              gyan3098@gmail.com
tagline:            "Hacking"
description: >- # this means to ignore newlines until "baseurl:"
  "In these 30 days challenge, I will be covering a lot of fields and topics
  of hacking"
url:                 https://github.com/gyan3098/30DaysOfHackingChallenge/tree/main/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Gyan Ranjan
  url:               https://twitter.com/arrow1326
  email:             gyan3098@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
